// +build !ignore_autogenerated

/*
Copyright 2018 The Soter Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	scanner "github.com/soter/scanner/apis/scanner"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_Feature_To_scanner_Feature,
		Convert_scanner_Feature_To_v1alpha1_Feature,
		Convert_v1alpha1_ImageReview_To_scanner_ImageReview,
		Convert_scanner_ImageReview_To_v1alpha1_ImageReview,
		Convert_v1alpha1_ImageReviewRequest_To_scanner_ImageReviewRequest,
		Convert_scanner_ImageReviewRequest_To_v1alpha1_ImageReviewRequest,
		Convert_v1alpha1_ScanResult_To_scanner_ScanResult,
		Convert_scanner_ScanResult_To_v1alpha1_ScanResult,
		Convert_v1alpha1_Vulnerability_To_scanner_Vulnerability,
		Convert_scanner_Vulnerability_To_v1alpha1_Vulnerability,
		Convert_v1alpha1_WorkloadReview_To_scanner_WorkloadReview,
		Convert_scanner_WorkloadReview_To_v1alpha1_WorkloadReview,
		Convert_v1alpha1_WorkloadReviewResponse_To_scanner_WorkloadReviewResponse,
		Convert_scanner_WorkloadReviewResponse_To_v1alpha1_WorkloadReviewResponse,
	)
}

func autoConvert_v1alpha1_Feature_To_scanner_Feature(in *Feature, out *scanner.Feature, s conversion.Scope) error {
	out.Name = in.Name
	out.NamespaceName = in.NamespaceName
	out.Version = in.Version
	out.Vulnerabilities = *(*[]scanner.Vulnerability)(unsafe.Pointer(&in.Vulnerabilities))
	return nil
}

// Convert_v1alpha1_Feature_To_scanner_Feature is an autogenerated conversion function.
func Convert_v1alpha1_Feature_To_scanner_Feature(in *Feature, out *scanner.Feature, s conversion.Scope) error {
	return autoConvert_v1alpha1_Feature_To_scanner_Feature(in, out, s)
}

func autoConvert_scanner_Feature_To_v1alpha1_Feature(in *scanner.Feature, out *Feature, s conversion.Scope) error {
	out.Name = in.Name
	out.NamespaceName = in.NamespaceName
	out.Version = in.Version
	out.Vulnerabilities = *(*[]Vulnerability)(unsafe.Pointer(&in.Vulnerabilities))
	return nil
}

// Convert_scanner_Feature_To_v1alpha1_Feature is an autogenerated conversion function.
func Convert_scanner_Feature_To_v1alpha1_Feature(in *scanner.Feature, out *Feature, s conversion.Scope) error {
	return autoConvert_scanner_Feature_To_v1alpha1_Feature(in, out, s)
}

func autoConvert_v1alpha1_ImageReview_To_scanner_ImageReview(in *ImageReview, out *scanner.ImageReview, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Request = (*scanner.ImageReviewRequest)(unsafe.Pointer(in.Request))
	return nil
}

// Convert_v1alpha1_ImageReview_To_scanner_ImageReview is an autogenerated conversion function.
func Convert_v1alpha1_ImageReview_To_scanner_ImageReview(in *ImageReview, out *scanner.ImageReview, s conversion.Scope) error {
	return autoConvert_v1alpha1_ImageReview_To_scanner_ImageReview(in, out, s)
}

func autoConvert_scanner_ImageReview_To_v1alpha1_ImageReview(in *scanner.ImageReview, out *ImageReview, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Request = (*ImageReviewRequest)(unsafe.Pointer(in.Request))
	return nil
}

// Convert_scanner_ImageReview_To_v1alpha1_ImageReview is an autogenerated conversion function.
func Convert_scanner_ImageReview_To_v1alpha1_ImageReview(in *scanner.ImageReview, out *ImageReview, s conversion.Scope) error {
	return autoConvert_scanner_ImageReview_To_v1alpha1_ImageReview(in, out, s)
}

func autoConvert_v1alpha1_ImageReviewRequest_To_scanner_ImageReviewRequest(in *ImageReviewRequest, out *scanner.ImageReviewRequest, s conversion.Scope) error {
	out.Image = in.Image
	out.ImagePullSecrets = *(*[]v1.ObjectReference)(unsafe.Pointer(&in.ImagePullSecrets))
	return nil
}

// Convert_v1alpha1_ImageReviewRequest_To_scanner_ImageReviewRequest is an autogenerated conversion function.
func Convert_v1alpha1_ImageReviewRequest_To_scanner_ImageReviewRequest(in *ImageReviewRequest, out *scanner.ImageReviewRequest, s conversion.Scope) error {
	return autoConvert_v1alpha1_ImageReviewRequest_To_scanner_ImageReviewRequest(in, out, s)
}

func autoConvert_scanner_ImageReviewRequest_To_v1alpha1_ImageReviewRequest(in *scanner.ImageReviewRequest, out *ImageReviewRequest, s conversion.Scope) error {
	out.Image = in.Image
	out.ImagePullSecrets = *(*[]v1.ObjectReference)(unsafe.Pointer(&in.ImagePullSecrets))
	return nil
}

// Convert_scanner_ImageReviewRequest_To_v1alpha1_ImageReviewRequest is an autogenerated conversion function.
func Convert_scanner_ImageReviewRequest_To_v1alpha1_ImageReviewRequest(in *scanner.ImageReviewRequest, out *ImageReviewRequest, s conversion.Scope) error {
	return autoConvert_scanner_ImageReviewRequest_To_v1alpha1_ImageReviewRequest(in, out, s)
}

func autoConvert_v1alpha1_ScanResult_To_scanner_ScanResult(in *ScanResult, out *scanner.ScanResult, s conversion.Scope) error {
	out.Name = in.Name
	out.Features = *(*[]scanner.Feature)(unsafe.Pointer(&in.Features))
	return nil
}

// Convert_v1alpha1_ScanResult_To_scanner_ScanResult is an autogenerated conversion function.
func Convert_v1alpha1_ScanResult_To_scanner_ScanResult(in *ScanResult, out *scanner.ScanResult, s conversion.Scope) error {
	return autoConvert_v1alpha1_ScanResult_To_scanner_ScanResult(in, out, s)
}

func autoConvert_scanner_ScanResult_To_v1alpha1_ScanResult(in *scanner.ScanResult, out *ScanResult, s conversion.Scope) error {
	out.Name = in.Name
	out.Features = *(*[]Feature)(unsafe.Pointer(&in.Features))
	return nil
}

// Convert_scanner_ScanResult_To_v1alpha1_ScanResult is an autogenerated conversion function.
func Convert_scanner_ScanResult_To_v1alpha1_ScanResult(in *scanner.ScanResult, out *ScanResult, s conversion.Scope) error {
	return autoConvert_scanner_ScanResult_To_v1alpha1_ScanResult(in, out, s)
}

func autoConvert_v1alpha1_Vulnerability_To_scanner_Vulnerability(in *Vulnerability, out *scanner.Vulnerability, s conversion.Scope) error {
	out.Name = in.Name
	out.NamespaceName = in.NamespaceName
	out.Description = in.Description
	out.Link = in.Link
	out.Severity = in.Severity
	out.FixedBy = in.FixedBy
	out.FeatureName = in.FeatureName
	return nil
}

// Convert_v1alpha1_Vulnerability_To_scanner_Vulnerability is an autogenerated conversion function.
func Convert_v1alpha1_Vulnerability_To_scanner_Vulnerability(in *Vulnerability, out *scanner.Vulnerability, s conversion.Scope) error {
	return autoConvert_v1alpha1_Vulnerability_To_scanner_Vulnerability(in, out, s)
}

func autoConvert_scanner_Vulnerability_To_v1alpha1_Vulnerability(in *scanner.Vulnerability, out *Vulnerability, s conversion.Scope) error {
	out.Name = in.Name
	out.NamespaceName = in.NamespaceName
	out.Description = in.Description
	out.Link = in.Link
	out.Severity = in.Severity
	out.FixedBy = in.FixedBy
	out.FeatureName = in.FeatureName
	return nil
}

// Convert_scanner_Vulnerability_To_v1alpha1_Vulnerability is an autogenerated conversion function.
func Convert_scanner_Vulnerability_To_v1alpha1_Vulnerability(in *scanner.Vulnerability, out *Vulnerability, s conversion.Scope) error {
	return autoConvert_scanner_Vulnerability_To_v1alpha1_Vulnerability(in, out, s)
}

func autoConvert_v1alpha1_WorkloadReview_To_scanner_WorkloadReview(in *WorkloadReview, out *scanner.WorkloadReview, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Response = (*scanner.WorkloadReviewResponse)(unsafe.Pointer(in.Response))
	return nil
}

// Convert_v1alpha1_WorkloadReview_To_scanner_WorkloadReview is an autogenerated conversion function.
func Convert_v1alpha1_WorkloadReview_To_scanner_WorkloadReview(in *WorkloadReview, out *scanner.WorkloadReview, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkloadReview_To_scanner_WorkloadReview(in, out, s)
}

func autoConvert_scanner_WorkloadReview_To_v1alpha1_WorkloadReview(in *scanner.WorkloadReview, out *WorkloadReview, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Response = (*WorkloadReviewResponse)(unsafe.Pointer(in.Response))
	return nil
}

// Convert_scanner_WorkloadReview_To_v1alpha1_WorkloadReview is an autogenerated conversion function.
func Convert_scanner_WorkloadReview_To_v1alpha1_WorkloadReview(in *scanner.WorkloadReview, out *WorkloadReview, s conversion.Scope) error {
	return autoConvert_scanner_WorkloadReview_To_v1alpha1_WorkloadReview(in, out, s)
}

func autoConvert_v1alpha1_WorkloadReviewResponse_To_scanner_WorkloadReviewResponse(in *WorkloadReviewResponse, out *scanner.WorkloadReviewResponse, s conversion.Scope) error {
	out.Images = *(*[]scanner.ScanResult)(unsafe.Pointer(&in.Images))
	return nil
}

// Convert_v1alpha1_WorkloadReviewResponse_To_scanner_WorkloadReviewResponse is an autogenerated conversion function.
func Convert_v1alpha1_WorkloadReviewResponse_To_scanner_WorkloadReviewResponse(in *WorkloadReviewResponse, out *scanner.WorkloadReviewResponse, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkloadReviewResponse_To_scanner_WorkloadReviewResponse(in, out, s)
}

func autoConvert_scanner_WorkloadReviewResponse_To_v1alpha1_WorkloadReviewResponse(in *scanner.WorkloadReviewResponse, out *WorkloadReviewResponse, s conversion.Scope) error {
	out.Images = *(*[]ScanResult)(unsafe.Pointer(&in.Images))
	return nil
}

// Convert_scanner_WorkloadReviewResponse_To_v1alpha1_WorkloadReviewResponse is an autogenerated conversion function.
func Convert_scanner_WorkloadReviewResponse_To_v1alpha1_WorkloadReviewResponse(in *scanner.WorkloadReviewResponse, out *WorkloadReviewResponse, s conversion.Scope) error {
	return autoConvert_scanner_WorkloadReviewResponse_To_v1alpha1_WorkloadReviewResponse(in, out, s)
}
