apiVersion: v1
kind: Secret
metadata:
  name: clair-postgresql
  namespace: ${SCANNER_NAMESPACE}
  labels:
    app: postgresql
type: Opaque
data:
  postgres-password: Y2xhaXI=
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clair-postgresql
  namespace: ${SCANNER_NAMESPACE}
  labels:
    app: postgresql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ${SCANNER_POSTGRES_STORAGE_CLASS}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgresql
  name: clair-postgresql
  namespace: ${SCANNER_NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          value: clair
        - name: PGUSER
          value: clair
        - name: POSTGRES_DB
          value: clair
        - name: POSTGRES_INITDB_ARGS
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: clair-postgresql
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: postgres:9.6.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          initialDelaySeconds: 120
          timeoutSeconds: 5
          failureThreshold: 6
        name: clair-postgresql
        ports:
        - containerPort: 5432
          name: postgresql
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 5
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/pgdata
          name: data
          subPath: postgresql-db
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: clair-postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: clair-postgresql
  namespace: ${SCANNER_NAMESPACE}
  labels:
    app: postgresql
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    app: postgresql
